### ISSUE TITLE
Csontváz ló (pet) folyamatosan respawnol a bolt területén.

### ISSUE THREAD

**Issue by primusantica** [TheOld-Crafters/Minecraft-servers#4407]
Survival

**Comment by andris155** [comment]
Szerintem mindenhol. Elavult a kód hozzá amit használ...

**Comment by andris155** [comment]
```
[16:55:20 WARN]: Entity threw exception at spawn2:12263.345895499615,69.0,30795.98238150154
[16:55:20 WARN]: java.lang.NoSuchMethodError: 'float net.minecraft.server.v1_16_R3.SoundEffectType.a()'
[16:55:20 WARN]:        at de.Keyle.MyPet.compat.v1_16_R3.entity.types.EntityMySkeletonHorse.playStepSound(EntityMySkeletonHorse.java:205)
[16:55:20 WARN]:        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.b(EntityMyPet.java:927)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.Entity.move(Entity.java:786)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.EntityLiving.a(EntityLiving.java:2407)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.EntityLiving.g(EntityLiving.java:2366)
[16:55:20 WARN]:        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.f(EntityMyPet.java:1187)
[16:55:20 WARN]:        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.movementTick(EntityMyPet.java:1045)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2520)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:336)
[16:55:20 WARN]:        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.tick(EntityMyPet.java:1338)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1383)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.World.a(World.java:1004)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1015)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1435)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1284)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1010)
[16:55:20 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176)
[16:55:20 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by primusantica** [comment]
Valamelyik nap vadonban használtam akkor működött ott.

**Comment by andris155** [comment]
Igazából ahogy néztem a kódot nem nagy dolog ezt javítani. Csak frissíteni kell, mivel megváltozott az 1.16.5-ben a hang lekérés. Megpróbálom majd most már tényleg valahogy megoldani, hogy a MyPet-et a módosítás után össze is tudjam építeni normális működő jar fájlra. Ezzel együtt akkor megtudnám javítani a telkeken is és akkor nem kellene mob befogó plugin-on se gondolkozni.
https://github.com/TheOld-Crafters/Minecraft-servers/issues/4371

**Comment by andris155** [comment]
Hát nem nagyon tudtam továbbra sem összerakni úgy, hogy jó is legyen. Nyitottam egy pull-t a javítással. Bár igazából azt se tudom így, hogy működik-e. De ha azt elfogadják, akkor a fejlesztő összetudja építeni a plugint.

**Comment by andris155** [comment]
Elfogadta a fejlesztő a javítást hozzá. De egyelőre nincs belőle összeépített verzió.

**Comment by andris155** [comment]
Beraktam a frissített változatot. Teszteltem és sikerült javítanom ezt a hibát.

**Comment by andris155** [comment]
Most már nem szabadna eltűnni a lovaknak.
